name: steemit
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cloud_firestore: ^4.4.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.8
  firebase_core: ^2.6.1
  firebase_storage: ^11.0.13
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  cached_network_image: ^3.2.3
  either_dart: ^0.3.0
  tiengviet: ^0.5.0
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: OpenSansBold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
    - family: OpenSansRegular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: OpenSansSemiBold
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf
